config/routes.rb
Rails.application.routes.draw do
  root 'photos#index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  post 'photos' => 'photos#create', as: :photos
  get "photos/open_modal" => 'photos#open_modal', as: :open_new_photo_modal

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  mount_uploader :picture, PhotoUploader

  validates :picture, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.all.order("created_at desc")
  end

  def open_modal
    @photo = Photo.new
  end

  def create
    @photo = Photo.new params.require(:photo).permit(:picture)
    @photo.save
    @photos = Photo.all.order("created_at desc")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Photolog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="col-xs-9">
      <h1>Photos</h1>
    </div>
    <div class="col-xs-3">
      <%= link_to "New Photo", open_new_photo_modal_path, remote: true, class: "btn btn-default" %>
    </div>
  </div>
  <%= yield %>

  <div class="modal fade" id="our-super-cool-modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Photo</h4>
      </div>
      <div class="modal-body">
        <p>One fine body&hellip;</p>
      </div>

    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

</div>

</body>
</html>

app/views/photos/_form.html.erb
<%= simple_form_for @photo, remote: true do |f| %>
  <%= f.input :picture %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/photos/_photos.html.erb
<div class="row">
  <% @photos.each do |photo| %>
    <div class="col-xs-6 col-md-2">
      <%= link_to "#", class: "thumbnail" do %>
        <%= image_tag photo.picture.url(:thumb) %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/photos/create.js.erb
<% if @photo.errors.none? %>
  // close modal
  $("#our-super-cool-modal").modal("hide");
  // re-render the photos
  $("#photos").html("<%= j render partial: 'photos' %>");
<% else %>
  $("#our-super-cool-modal .modal-body").html("<%= j render partial: 'form' %>");

<% end %>

app/views/photos/index.html.erb
<div id="photos">
  <%= render partial: 'photos' %>
</div>

app/views/photos/open_modal.js.erb
// Render a form into the modal-content
$("#our-super-cool-modal .modal-body").html("<%= j render partial: 'form' %>");
// Open the modal
$("#our-super-cool-modal").modal("show");